// <auto-generated />

namespace Test
{
    partial class TestClass
    {
        public global::Mocklis.Core.PropertyMock<int> Normal { get; }

        int global::Test.ITestClass.Normal { get => Normal.Value; set => Normal.Value = value; }

        public TestClass() : base()
        {
            this.Normal = new global::Mocklis.Core.PropertyMock<int>(this, "TestClass", "ITestClass", "Normal", "Normal", global::Mocklis.Core.Strictness.Lenient);
        }
    }
}
