// <auto-generated />

namespace Test
{
    partial class TestClass
    {
        public global::Mocklis.Core.ActionMethodMock<string> Normal { get; }

        void global::Test.ITestClass.Normal(string e) => Normal.Call(e);

        public TestClass() : base()
        {
            this.Normal = new global::Mocklis.Core.ActionMethodMock<string>(this, "TestClass", "ITestClass", "Normal", "Normal", global::Mocklis.Core.Strictness.Lenient);
        }
    }
}
