// <auto-generated />

namespace Test
{
    partial class TestClass
    {
        // Add source for members in interface ITestClass
        // Adding line for Property Based Method Mock

        public global::Mocklis.Core.ActionMethodMock<string> Normal { get; }

        void global::Test.ITestClass.Normal(string e)
        // Adding constructors here...
    }
}
