// <auto-generated />

namespace Test
{
    partial class TestClass
    {
        public global::Mocklis.Core.IndexerMock<(int i, bool b), int> Item { get; }

        int global::Test.ITestClass.this[int i, bool b] { get => Item[(i, b)]; set => Item[(i, b)] = value; }

        public TestClass() : base()
        {
            this.Item = new global::Mocklis.Core.IndexerMock<(int i, bool b), int>(this, "TestClass", "ITestClass", "this[]", "Item", global::Mocklis.Core.Strictness.Lenient);
        }
    }
}
