// <auto-generated />

#nullable enable

namespace Test
{
    partial class TestClass
    {
        // Add source for members in interface ITestClass
        // Adding line for Property Based Event Mock
        // Adding line for Property Based Event Mock
        // Adding constructors here...
    }
}
