// <auto-generated />

#nullable enable

namespace Test
{
    partial class TestClass
    {
        // Adding line for Property Based Event Mock

        // Adding line for Property Based Event Mock
    }
}
