// <auto-generated />

#nullable enable

namespace Test
{
    partial class TestClass
    {
        // Add source for members in interface ITestClass
        // Adding line for Property Based Property Mock
        // Adding line for Property Based Indexer Mock
        // Adding line for Property Based Method Mock

        public global::Mocklis.Core.FuncMethodMock<T?,T?> Test { get; }

        T? global::Test.ITestClass<T>.Test(T? item)
        // Adding constructors here...
    }
}
