// <auto-generated />

#nullable enable

namespace Test
{
    partial class TestClass
    {
        // Adding line for Property Based Property Mock

        // Adding line for Property Based Indexer Mock

        public global::Mocklis.Core.FuncMethodMock<T?, T?> Test { get; }

        T? global::Test.ITestClass<T>.Test(T? item) => Test.Call(item);

        protected TestClass() : base()
        {
            this.Test = new global::Mocklis.Core.FuncMethodMock<T?, T?>(this, "TestClass", "ITestClass", "Test", "Test", global::Mocklis.Core.Strictness.Lenient);
        }
    }
}
