// <auto-generated />

#nullable enable

namespace Test
{
    partial class TestClass
    {
        public global::Mocklis.Core.PropertyMock<global::System.Collections.Generic.IDictionary<int?, global::System.Collections.Generic.List<(byte, string)>>> Test { get; }

        global::System.Collections.Generic.IDictionary<int?, global::System.Collections.Generic.List<(byte, string)>> global::Test.ITestClass.Test => Test.Value;

        protected TestClass() : base()
        {
            this.Test = new global::Mocklis.Core.PropertyMock<global::System.Collections.Generic.IDictionary<int?, global::System.Collections.Generic.List<(byte, string)>>>(this, "TestClass", "ITestClass", "Test", "Test", global::Mocklis.Core.Strictness.Lenient);
        }
    }
}
