// <auto-generated />

#nullable enable

namespace Test
{
    partial class TestClass
    {
        // Add source for members in interface ITestClass
        // Adding line for Property Based Method Mock

        public global::Mocklis.Core.ActionMethodMock<T?> DoStuff { get; }

        void global::Test.ITestClass.DoStuff(T? p)
        // Adding constructors here...
    }
}
