// <auto-generated />

#nullable enable

namespace Test
{
    partial class TestClass
    {
        public global::Mocklis.Core.ActionMethodMock<T?> DoStuff { get; }

        void global::Test.ITestClass.DoStuff(T? p) => DoStuff.Call(p);

        protected TestClass() : base()
        {
            this.DoStuff = new global::Mocklis.Core.ActionMethodMock<T?>(this, "TestClass", "ITestClass", "DoStuff", "DoStuff", global::Mocklis.Core.Strictness.Lenient);
        }
    }
}
