// <auto-generated />

namespace Test
{
    partial class TestClass
    {
        // Add source for members in interface ITestClass
        // Adding line for Property Based Method Mock

        public global::Mocklis.Core.FuncMethodMock<U,T> Test { get; }

        T global::Test.ITestClass<T>.Test(U item)
        // Adding constructors here...
    }
}
