// <auto-generated />

#nullable enable

namespace Test
{
    partial class TestClass
    {
        // Add source for members in interface ITestClass
        // Adding line for Property Based Property Mock
        // Adding line for Property Based Indexer Mock
        // Adding line for Property Based Event Mock
        // Adding line for Property Based Method Mock

        public global::Mocklis.Core.FuncMethodMock<(string? p1, string? p2),string?> Method3 { get; }

        string? global::Test.ITestClass.Method3(string? p1, string? p2)
        // Adding line for Property Based Property Mock
        // Adding line for Property Based Property Mock
        // Adding constructors here...
    }
}
