// <auto-generated />

#nullable enable

namespace Test
{
    partial class TestClass
    {
        // Adding line for Property Based Property Mock

        // Adding line for Property Based Indexer Mock

        // Adding line for Property Based Event Mock

        public global::Mocklis.Core.FuncMethodMock<(string? p1, string? p2), string?> Method3 { get; }

        string? global::Test.ITestClass.Method3(string? p1, string? p2) => Method3.Call((p1, p2));

        // Adding line for Property Based Property Mock

        // Adding line for Property Based Property Mock

        protected TestClass() : base()
        {
            this.Method3 = new global::Mocklis.Core.FuncMethodMock<(string? p1, string? p2), string?>(this, "TestClass", "ITestClass", "Method3", "Method3", global::Mocklis.Core.Strictness.Lenient);
        }
    }
}
