// <auto-generated />

namespace Test
{
    partial class TestClass
    {
        public global::Mocklis.Core.PropertyMock<int> Test { get; }

        int global::Test.ITestClass.Test => Test.Value;

        protected TestClass() : base()
        {
            this.Test = new global::Mocklis.Core.PropertyMock<int>(this, "TestClass", "ITestClass", "Test", "Test", global::Mocklis.Core.Strictness.Lenient);
        }
    }
}
