// <auto-generated />

namespace Test
{
    partial class TestClass
    {
        public global::Mocklis.Core.FuncMethodMock<int, string> Test { get; }

        string global::Test.ITestClass.Test(int i) => Test.Call(i);

        public TestClass() : base()
        {
            this.Test = new global::Mocklis.Core.FuncMethodMock<int, string>(this, "TestClass", "ITestClass", "Test", "Test", global::Mocklis.Core.Strictness.Lenient);
        }
    }
}
