// <auto-generated />

namespace Test
{
    partial class TestClass
    {
        protected virtual string Concat(string s1, string s2, global::System.RuntimeArgumentHandle arglist)
        {
            throw new global::Mocklis.Core.MockMissingException(global::Mocklis.Core.MockType.VirtualMethod, "TestClass", "ITestClass", "Concat", "Concat");
        }

        string global::Test.ITestClass.Concat(string s1, string s2, global::System.RuntimeArgumentHandle arglist) => Concat(s1, s2, arglist);
    }
}
