// <auto-generated />

namespace Test
{
    partial class TestClass
    {
        public global::Mocklis.Core.FuncMethodMock<int, string> Test0 { get; }

        string global::Test.ITestClass.Test(int i) => Test0.Call(i);

        // Adding line for Property Based Property Mock

        public TestClass() : base()
        {
            this.Test0 = new global::Mocklis.Core.FuncMethodMock<int, string>(this, "TestClass", "ITestClass", "Test", "Test0", global::Mocklis.Core.Strictness.Lenient);
        }
    }
}
