// <auto-generated />

namespace Test
{
    partial class TestClass
    {
        // Add source for members in interface ITestClass
        // Adding line for Property Based Method Mock

        public global::Mocklis.Core.FuncMethodMock<int,string> TestClass0 { get; }

        string global::Test.ITestClass.TestClass(int i)
        // Adding constructors here...
    }
}
