// <auto-generated />

namespace Test
{
    partial class TestClass
    {
        public global::Mocklis.Core.FuncMethodMock<int, string> TestClass0 { get; }

        string global::Test.ITestClass.TestClass(int i) => TestClass0.Call(i);

        public TestClass() : base()
        {
            this.TestClass0 = new global::Mocklis.Core.FuncMethodMock<int, string>(this, "TestClass", "ITestClass", "TestClass", "TestClass0", global::Mocklis.Core.Strictness.Lenient);
        }
    }
}
