// <auto-generated />

namespace Test
{
    partial class TestClass
    {
        // Adding line for Property Based Property Mock

        public TestClass(int i) : base(i)
        {
        }

        public TestClass(string s) : base(s)
        {
        }
    }
}
