// <auto-generated />

namespace Test
{
    partial class TestClass
    {
        // Add source for members in interface IEnumerable
        // Adding line for Property Based Method Mock

        public global::Mocklis.Core.FuncMethodMock<global::System.Collections.Generic.IEnumerator<T>> GetEnumerator { get; }

        global::System.Collections.Generic.IEnumerator<T> global::System.Collections.Generic.IEnumerable<T>.GetEnumerator()
        // Add source for members in interface IEnumerable
        // Adding line for Property Based Method Mock

        public global::Mocklis.Core.FuncMethodMock<global::System.Collections.IEnumerator> GetEnumerator0 { get; }

        global::System.Collections.IEnumerator global::System.Collections.IEnumerable.GetEnumerator()
        // Adding constructors here...
    }
}
