// <auto-generated />

namespace Test
{
    partial class TestClass
    {
        // Add source for members in interface ITestClass
        // Adding line for Property Based Method Mock

        public global::Mocklis.Core.FuncMethodMock<T1,string> DoCalculation { get; }

        string global::Test.ITestClass<T1, string>.DoCalculation(T1 sourceData)
        // Adding constructors here...
    }
}
