// <auto-generated />

namespace Test
{
    partial class TestClass
    {
        // Add source for members in interface ITest1
        // Adding line for Property Based Property Mock
        // Add source for members in interface ITest2
        // Adding line for Property Based Method Mock

        public global::Mocklis.Core.ActionMethodMock<string> DoSomething { get; }

        void global::Test.ITest2.DoSomething(string task)
        // Adding constructors here...
    }
}
