// <auto-generated />

namespace Test
{
    partial class TestClass
    {
        public global::Mocklis.Core.IndexerMock<(int Item2_, string Item5_), int> Item { get; }

        int global::Test.ITestClass.this[int Item2_, string Item5_] { get => Item[(Item2_, Item5_)]; set => Item[(Item2_, Item5_)] = value; }

        public global::Mocklis.Core.IndexerMock<(int Item2_0, int Item2_), int> Item0 { get; }

        int global::Test.ITestClass.this[int Item2_0, int Item2_] { get => Item0[(Item2_0, Item2_)]; set => Item0[(Item2_0, Item2_)] = value; }

        public TestClass() : base()
        {
            this.Item = new global::Mocklis.Core.IndexerMock<(int Item2_, string Item5_), int>(this, "TestClass", "ITestClass", "this[]", "Item", global::Mocklis.Core.Strictness.Lenient);
            this.Item0 = new global::Mocklis.Core.IndexerMock<(int Item2_0, int Item2_), int>(this, "TestClass", "ITestClass", "this[]", "Item0", global::Mocklis.Core.Strictness.Lenient);
        }
    }
}
