// <auto-generated />

namespace Test
{
    partial class TestClass
    {
        // Adding line for Virtual Method Based Indexer Mock

        // Adding line for Virtual Method Based Indexer Mock

        // Adding line for Virtual Method Based Indexer Mock

        // Adding line for Virtual Method Based Indexer Mock
    }
}
