// <auto-generated />

namespace Test
{
    partial class TestClass
    {
        public global::Mocklis.Core.IndexerMock<int, int> Item { get; }

        ref int global::Test.ITestClass.this[int i] => ref global::Mocklis.Core.ByRef<int>.Wrap(Item[i]);

        // Adding line for Virtual Method Based Indexer Mock

        public TestClass() : base()
        {
            this.Item = new global::Mocklis.Core.IndexerMock<int, int>(this, "TestClass", "ITestClass", "this[]", "Item", global::Mocklis.Core.Strictness.Lenient);
        }
    }
}
