// <auto-generated />

namespace Test
{
    partial class TestClass
    {
        protected virtual ref int Item(int i)
        {
            throw new global::Mocklis.Core.MockMissingException(global::Mocklis.Core.MockType.VirtualIndexerGet, "TestClass", "ITestClass", "this[]", "Item");
        }

        ref int global::Test.ITestClass.this[int i] => ref Item(i);

        public global::Mocklis.Core.IndexerMock<string, int> Item0 { get; }

        ref readonly int global::Test.ITestClass.this[string s] => ref global::Mocklis.Core.ByRef<int>.Wrap(Item0[s]);

        public TestClass() : base()
        {
            this.Item0 = new global::Mocklis.Core.IndexerMock<string, int>(this, "TestClass", "ITestClass", "this[]", "Item0", global::Mocklis.Core.Strictness.Lenient);
        }
    }
}
