// <auto-generated />

namespace Test
{
    partial class TestClass
    {
        // Add source for members in interface ITestClass
        // Adding line for Property Based Method Mock

        public global::Mocklis.Core.FuncMethodMock<string,(bool returnValue, int result)> TryParse { get; }

        bool global::Test.ITestClass.TryParse(string source, out int result)
        // Adding line for Property Based Method Mock

        public global::Mocklis.Core.FuncMethodMock<(int t1, int t2),int> Test { get; }

        int global::Test.ITestClass.Test(in int t1, in int t2)
        // Adding line for Property Based Method Mock

        public global::Mocklis.Core.FuncMethodMock<string,string> Mutate { get; }

        void global::Test.ITestClass.Mutate(ref string value)
        // Adding constructors here...
    }
}
