// <auto-generated />

namespace Test
{
    partial class TestClass
    {
        // Add source for members in interface ITest
        // Adding line for Property Based Method Mock

        public global::Mocklis.Core.ActionMethodMock<string> DoStuff { get; }

        void global::InterfaceyStuff.ITest.DoStuff(string stuff)
        // Adding constructors here...
    }
}
