// <auto-generated />

namespace Test
{
    partial class TestClass
    {
        public global::Mocklis.Core.FuncMethodMock<int> ReturnsByRef { get; }

        ref int global::Test.ITestClass.ReturnsByRef() => ref global::Mocklis.Core.ByRef<int>.Wrap(ReturnsByRef.Call());

        protected virtual ref int ReturnsByRefReadonly()
        {
            throw new global::Mocklis.Core.MockMissingException(global::Mocklis.Core.MockType.VirtualMethod, "TestClass", "ITestClass", "ReturnsByRefReadonly", "ReturnsByRefReadonly");
        }

        ref readonly int global::Test.ITestClass.ReturnsByRefReadonly() => ref ReturnsByRefReadonly();

        public TestClass() : base()
        {
            this.ReturnsByRef = new global::Mocklis.Core.FuncMethodMock<int>(this, "TestClass", "ITestClass", "ReturnsByRef", "ReturnsByRef", global::Mocklis.Core.Strictness.Lenient);
        }
    }
}
