// <auto-generated />

namespace Test
{
    partial class TestClass
    {
        protected virtual global::Test.RefStruct ReturnsRefStruct()
        {
            throw new global::Mocklis.Core.MockMissingException(global::Mocklis.Core.MockType.VirtualMethod, "TestClass", "ITestClass", "ReturnsRefStruct", "ReturnsRefStruct");
        }

        global::Test.RefStruct global::Test.ITestClass.ReturnsRefStruct() => ReturnsRefStruct();
    }
}
