// <auto-generated />

namespace Test
{
    partial class TestClass
    {
        // Add source for members in interface ITestClass
        // Adding line for Property Based Method Mock

        public global::Mocklis.Core.FuncMethodMock<(T1 parameter, T3 parameter2, T4 anotherParameter),T2> Test { get; }

        T2 global::Test.ITestClass.Test(T1 parameter, T3 parameter2, T4 anotherParameter)
        // Adding constructors here...
    }
}
