// <auto-generated />

namespace Test
{
    partial class TestClass
    {
        // Add source for members in interface ITestClass
        // Adding line for Property Based Method Mock

        public global::Mocklis.Core.FuncMethodMock<int> ReturnsByRef { get; }

        ref int global::Test.ITestClass.ReturnsByRef()
        // Adding line for Virtual Method Based Method Mock
        // Adding constructors here...
    }
}
