// <auto-generated />

namespace Test
{
    partial class TestClass
    {
        protected virtual T TakesRefStructParameter<T>(global::Test.RefStruct parameter)
        {
            throw new global::Mocklis.Core.MockMissingException(global::Mocklis.Core.MockType.VirtualMethod, "TestClass", "ITestClass", "TakesRefStructParameter", "TakesRefStructParameter");
        }

        T global::Test.ITestClass.TakesRefStructParameter<T>(global::Test.RefStruct parameter) => TakesRefStructParameter<T>(parameter);
    }
}
