// <auto-generated />

namespace Test
{
    partial class TestClass
    {
        // Add source for members in interface ITestClass
        // Adding line for Property Based Method Mock

        public global::Mocklis.Core.ActionMethodMock<(int Item2_, int AnotherItem)> Test { get; }

        void global::Test.ITestClass.Test(int Item2, int AnotherItem)
        // Adding line for Property Based Method Mock

        public global::Mocklis.Core.FuncMethodMock<(int returnValue, int Item1_)> Test2 { get; }

        int global::Test.ITestClass.Test2(out int Item1)
        // Adding constructors here...
    }
}
