// <auto-generated />

namespace Test
{
    partial class TestClass
    {
        protected virtual void TakesRefStructParameter(global::Test.RefStruct parameter)
        {
            throw new global::Mocklis.Core.MockMissingException(global::Mocklis.Core.MockType.VirtualMethod, "TestClass", "ITestClass", "TakesRefStructParameter", "TakesRefStructParameter");
        }

        void global::Test.ITestClass.TakesRefStructParameter(global::Test.RefStruct parameter) => TakesRefStructParameter(parameter);
    }
}
