// <auto-generated />

namespace Test
{
    partial class TestClass
    {
        public global::Mocklis.Core.FuncMethodMock<int> ReturnsByRef { get; }

        ref int global::Test.ITestClass.ReturnsByRef() => ref global::Mocklis.Core.ByRef<int>.Wrap(ReturnsByRef.Call());

        // Adding line for Virtual Method Based Method Mock

        public TestClass() : base()
        {
            this.ReturnsByRef = new global::Mocklis.Core.FuncMethodMock<int>(this, "TestClass", "ITestClass", "ReturnsByRef", "ReturnsByRef", global::Mocklis.Core.Strictness.Lenient);
        }
    }
}
