// <auto-generated />

namespace Test
{
    partial class TestClass
    {
        // Add source for members in interface ITestClass
        // Adding line for Property Based Method Mock

        public global::Mocklis.Core.FuncMethodMock<T> ReturnsNewType { get; }

        T global::Test.ITestClass.ReturnsNewType()
        // Adding line for Property Based Method Mock

        public global::Mocklis.Core.ActionMethodMock<T> UsesNewType { get; }

        void global::Test.ITestClass.UsesNewType(T parameter)
        // Adding constructors here...
    }
}
