// <auto-generated />

namespace Test
{
    partial class TestClass
    {
        // Add source for members in interface ITestClass
        // Adding line for Property Based Method Mock

        public global::Mocklis.Core.FuncMethodMock<(T1 param1, T2 param2),string> Combine { get; }

        string global::Test.ITestClass.Combine(T1 param1, T2 param2)
        // Adding line for Property Based Method Mock

        public global::Mocklis.Core.FuncMethodMock<(T1 param1, T2 param2, T3 param3),string> Combine0 { get; }

        string global::Test.ITestClass.Combine(T1 param1, T2 param2, T3 param3)
        // Adding line for Property Based Method Mock

        public global::Mocklis.Core.FuncMethodMock<(T1 param1, T2 param2, T3 param3, T4 param4),string> Combine1 { get; }

        string global::Test.ITestClass.Combine(T1 param1, T2 param2, T3 param3, T4 param4)
        // Adding constructors here...
    }
}
