// <auto-generated />

namespace Test
{
    partial class TestClass
    {
        // Add source for members in interface ITestClass
        // Adding line for Virtual Method Based Method Mock
        // Adding line for Property Based Method Mock

        public global::Mocklis.Core.FuncMethodMock<int> ReturnsByRefReadonly { get; }

        ref readonly int global::Test.ITestClass.ReturnsByRefReadonly()
        // Adding line for Property Based Method Mock

        public global::Mocklis.Core.FuncMethodMock<(int returnValue, int blah)> ReturnsMoreStuffByRef { get; }

        ref readonly int global::Test.ITestClass.ReturnsMoreStuffByRef(out int blah)
        // Adding constructors here...
    }
}
