// <auto-generated />

namespace Test
{
    partial class TestClass
    {
        public global::Mocklis.Core.ActionMethodMock<U> Test { get; }

        void global::Test.ITestClass<int>.Test(U parameter) => Test.Call(parameter);

        public TestClass() : base()
        {
            this.Test = new global::Mocklis.Core.ActionMethodMock<U>(this, "TestClass", "ITestClass", "Test", "Test", global::Mocklis.Core.Strictness.Lenient);
        }
    }
}
