// <auto-generated />

namespace Test
{
    partial class TestClass
    {
        // Add source for members in interface IDuplexConnection
        // Adding line for Property Based Event Mock
        // Adding line for Property Based Event Mock
        // Adding line for Property Based Method Mock

        public global::Mocklis.Core.ActionMethodMock<byte[]> SendData { get; }

        void global::Test.IDuplexConnection.SendData(byte[] data)
        // Adding line for Property Based Method Mock

        public global::Mocklis.Core.ActionMethodMock<string> SendText { get; }

        void global::Test.IDuplexConnection.SendText(string text)
        // Adding line for Property Based Method Mock

        public global::Mocklis.Core.FuncMethodMock<string,global::System.Threading.Tasks.Task<string>> Close { get; }

        global::System.Threading.Tasks.Task<string> global::Test.IDuplexConnection.Close(string reason)
        // Adding line for Property Based Method Mock

        public global::Mocklis.Core.FuncMethodMock<global::System.Threading.Tasks.Task> Run { get; }

        global::System.Threading.Tasks.Task global::Test.IDuplexConnection.Run()
        // Adding line for Property Based Property Mock
        // Adding constructors here...
    }
}
