// <auto-generated />

namespace Test
{
    partial class TestClass
    {
        // Add source for members in interface ITestClass
        // Adding line for Property Based Method Mock

        public global::Mocklis.Core.FuncMethodMock<T1,T2> DoCalculation { get; }

        T2 global::Test.ITestClass<T1, T2>.DoCalculation(T1 sourceData)
        // Adding constructors here...
    }
}
