// <auto-generated />

namespace Test
{
    partial class TestClass<T1, T2>
    {
        public global::Mocklis.Core.FuncMethodMock<T1, T2> DoCalculation { get; }

        T2 global::Test.ITestClass<T1, T2>.DoCalculation(T1 sourceData) => DoCalculation.Call(sourceData);

        public TestClass() : base()
        {
            this.DoCalculation = new global::Mocklis.Core.FuncMethodMock<T1, T2>(this, "TestClass", "ITestClass", "DoCalculation", "DoCalculation", global::Mocklis.Core.Strictness.Lenient);
        }
    }
}
