// <auto-generated />

namespace Test
{
    partial class TestClass
    {
        // Add source for members in interface ITestClass
        // Adding line for Property Based Method Mock

        public global::Mocklis.Core.FuncMethodMock<string,(bool returnValue, int result)> TryParse1 { get; }

        bool global::Test.ITestClass.TryParse1(string tmp, out int result)
        // Adding line for Property Based Method Mock

        public global::Mocklis.Core.FuncMethodMock<string,(bool returnValue, int tmp)> TryParse2 { get; }

        bool global::Test.ITestClass.TryParse2(string source, out int tmp)
        // Adding constructors here...
    }
}
