// <auto-generated />

namespace Test
{
    partial class TestClass
    {
        // Adding line for Virtual Method Based Property Mock

        // Adding line for Virtual Method Based Property Mock

        // Adding line for Virtual Method Based Property Mock

        // Adding line for Virtual Method Based Property Mock
    }
}
