// <auto-generated />

namespace Test
{
    partial class TestClass
    {
        public global::Mocklis.Core.PropertyMock<int> TestClass0 { get; }

        int global::Test.ITestClass.TestClass { get => TestClass0.Value; set => TestClass0.Value = value; }

        public TestClass() : base()
        {
            this.TestClass0 = new global::Mocklis.Core.PropertyMock<int>(this, "TestClass", "ITestClass", "TestClass", "TestClass0", global::Mocklis.Core.Strictness.Lenient);
        }
    }
}
