// <auto-generated />

namespace Test
{
    partial class TestClass
    {
        // Add source for members in interface ITestClass
        // Adding line for Property Based Method Mock

        public global::Mocklis.Core.FuncMethodMock<(int tmp, int score),int> UpdateScore { get; }

        void global::Test.ITestClass.UpdateScore(int tmp, ref int score)
        // Adding line for Property Based Method Mock

        public global::Mocklis.Core.FuncMethodMock<(string action, int tmp),int> UpdateScore0 { get; }

        void global::Test.ITestClass.UpdateScore(string action, ref int tmp)
        // Adding constructors here...
    }
}
