// <auto-generated />

namespace Test
{
    partial class TestClass
    {
        // Add source for members in interface ITestClass
        // Adding line for Property Based Method Mock

        public global::Mocklis.Core.ActionMethodMock<(int Item2_, int anotherItem)> Item2_ { get; }

        void global::Test.ITestClass.Item2_(int Item2, int anotherItem)
        // Adding line for Property Based Method Mock

        public global::Mocklis.Core.FuncMethodMock<string,(int returnValue, string Item3_)> Item3_ { get; }

        int global::Test.ITestClass.Item3_(ref string Item3)
        // Adding line for Property Based Method Mock

        public global::Mocklis.Core.FuncMethodMock<T,(int returnValue, T Item4_)> Item4_ { get; }

        int global::Test.ITestClass.Item4_(ref T Item4)
        // Adding constructors here...
    }
}
