// <auto-generated />

namespace Test
{
    partial class TestClass<T>
    {
        public global::Mocklis.Core.PropertyMock<T> GetAndSet { get; }

        T global::Test.ITestClass<T>.GetAndSet { get => GetAndSet.Value; set => GetAndSet.Value = value; }

        public TestClass() : base()
        {
            this.GetAndSet = new global::Mocklis.Core.PropertyMock<T>(this, "TestClass", "ITestClass", "GetAndSet", "GetAndSet", global::Mocklis.Core.Strictness.Lenient);
        }
    }
}
