// <auto-generated />

namespace Test
{
    partial class TestClass
    {
        // Adding line for Property Based Property Mock

        // Adding line for Property Based Property Mock

        // Adding line for Property Based Property Mock
    }
}
