// <auto-generated />

namespace Test
{
    partial class TestClass
    {
        // Add source for members in interface ITestClass
        // Adding line for Property Based Property Mock
        // Adding line for Property Based Indexer Mock
        // Adding line for Property Based Method Mock

        public global::Mocklis.Core.FuncMethodMock<string,string> MyMethod { get; }

        string global::Test.ITestClass.MyMethod(string param)
        // Adding line for Property Based Event Mock
        // Adding constructors here...
    }
}
