// <auto-generated />

namespace Test
{
    partial class TestClass<T>
    {
        // Adding line for Virtual Method Based Method Mock

        // Adding line for Virtual Method Based Method Mock

        private readonly global::Mocklis.Core.TypedMockProvider _testWithRef = new global::Mocklis.Core.TypedMockProvider();

        public global::Mocklis.Core.FuncMethodMock<T0> TestWithRef<T0>()
        {
            var key = new[] { typeof(T0) };
            return (global::Mocklis.Core.FuncMethodMock<T0>)TestWithRef.GetOrAdd(key, keyString => new global::Mocklis.Core.FuncMethodMock<T0>(this, "TestClass", "ITestClass", "TestWithRef" + keyString, "TestWithRef" + keyString, global::Mocklis.Core.Strictness.Lenient));
        }

        ref readonly T0 global::Test.ITestClass<T>.TestWithRef<T0>() => ref global::Mocklis.Core.ByRef<T0>.Wrap(TestWithRef<T0>().Call());
    }
}
