// <auto-generated />

namespace Test
{
    partial class TestClass
    {
        // Add source for members in interface ITestClass
        // Adding line for Property Based Method Mock

        public global::Mocklis.Core.ActionMethodMock<TInner> Test { get; }

        void global::Test.ITestClass<T>.Test(TInner parameter)
        // Adding constructors here...
    }
}
