// <auto-generated />

namespace Test
{
    partial class TestClass
    {
        // Adding line for Virtual Method Based Method Mock

        // Adding line for Virtual Method Based Method Mock
    }
}
