// <auto-generated />

namespace Test
{
    partial class TestClass<T>
    {
        // Adding line for Virtual Method Based Method Mock

        // Adding line for Virtual Method Based Method Mock
    }
}
