//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mocklis.Properties {
    using System;
    using System.Reflection;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Mocklis.Properties.Resources", typeof(Resources).GetTypeInfo().Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No mock implementation found for adding handler to Event &apos;{1}.{2}&apos;. Add one using &apos;{3}&apos; on the &apos;{0}&apos; class..
        /// </summary>
        internal static string MockMissingExceptionMessageForEventAdd {
            get {
                return ResourceManager.GetString("MockMissingExceptionMessageForEventAdd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No mock implementation found for removing handler from Event &apos;{1}.{2}&apos;. Add one using &apos;{3}&apos; on the &apos;{0}&apos; class..
        /// </summary>
        internal static string MockMissingExceptionMessageForEventRemove {
            get {
                return ResourceManager.GetString("MockMissingExceptionMessageForEventRemove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No mock implementation found for getting value via the Indexer on &apos;{1}.{2}&apos;. Add one using &apos;{3}&apos; on the &apos;{0}&apos; class..
        /// </summary>
        internal static string MockMissingExceptionMessageForIndexerGet {
            get {
                return ResourceManager.GetString("MockMissingExceptionMessageForIndexerGet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No mock implementation found for setting value via the Indexer on &apos;{1}.{2}&apos;. Add one using &apos;{3}&apos; on the &apos;{0}&apos; class..
        /// </summary>
        internal static string MockMissingExceptionMessageForIndexerSet {
            get {
                return ResourceManager.GetString("MockMissingExceptionMessageForIndexerSet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No mock implementation found for Method &apos;{1}.{2}&apos;. Add one using &apos;{3}&apos; on the &apos;{0}&apos; class..
        /// </summary>
        internal static string MockMissingExceptionMessageForMethod {
            get {
                return ResourceManager.GetString("MockMissingExceptionMessageForMethod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No mock implementation found for getting value of Property &apos;{1}.{2}&apos;. Add one using &apos;{3}&apos; on the &apos;{0}&apos; class..
        /// </summary>
        internal static string MockMissingExceptionMessageForPropertyGet {
            get {
                return ResourceManager.GetString("MockMissingExceptionMessageForPropertyGet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No mock implementation found for setting value of Property &apos;{1}.{2}&apos;. Add one using &apos;{3}&apos; on the &apos;{0}&apos; class..
        /// </summary>
        internal static string MockMissingExceptionMessageForPropertySet {
            get {
                return ResourceManager.GetString("MockMissingExceptionMessageForPropertySet", resourceCulture);
            }
        }
    }
}
